# 自己编写实现KNN

## 导入相关的包以及数据集

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib
%matplotlib inline

## 读取数据集,切分成训练集和测试集

In [2]:
#1.读取数据集,切分成训练集和测试集
iris = load_iris()
X = iris.data
y = iris.target
X_train,X_test,y_train,y_test,= train_test_split(X,y,test_size = 0.3)

In [3]:
X_train.shape

(105, 4)

In [10]:
type(X_train)

numpy.ndarray

In [4]:
X_test.shape

(45, 4)

## 编写KNN算法

In [5]:
def KNN_classify(train_data,train_label,test_data,k):
    train_size = len(X_train)
    labels = []
    for i in range(len(test_data)):
        #计算欧式距离
        diff = np.tile(test_data[i],(train_size,1)) - train_data
        sqdiff = diff ** 2
        sqDist = np.cumsum(sqdiff,axis = 1)
        dist = sqDist[:,-1] ** 0.5
        
        #对距离进行排序,返回下标
        sortedDistIndex = np.argsort(dist)
        
        #用字典来构建key-value对，key是类别，value是出现次数
        classCount = {}
        classCount = classCount.fromkeys(set(train_label),0)
        for i in range(k):
            voteLabel = train_label[sortedDistIndex[i]]
            classCount[voteLabel] = classCount[voteLabel] + 1
        
        maxcount = 0
        for key,value in classCount.items():
            if value > maxcount:
                maxcount = value
                label = key
                
        labels.append(label)
    return labels

## K=3时，结果比较

In [9]:
classify_result = KNN_classify(X_train,y_train,X_test,3)
print('预测结果 真实结果')
print([classify_result,y_test])


预测结果 真实结果
[[1, 2, 2, 1, 0, 0, 2, 1, 2, 0, 1, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 0, 1, 2, 0, 2, 0, 1, 1, 0, 0, 2, 1, 2], array([1, 1, 2, 1, 0, 0, 2, 1, 2, 0, 1, 0, 0, 2, 1, 2, 1, 2, 0, 2, 0, 1,
       1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 0, 1, 2, 0, 1, 0, 1, 1, 0, 0, 2, 1,
       2])]


## K=4时，结果比较

In [7]:
classify_result = KNN_classify(X_train,y_train,X_test,4)
print('预测结果 真实结果')
print(np.transpose([classify_result,y_test]))

预测结果 真实结果
[[1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]]


# Sklearn中的KNN算法

https://www.cnblogs.com/xiaotan-code/p/6680438.html

In [8]:
import numpy as np
from sklearn import neighbors
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


#1.读取数据集,切分成训练集和测试集
iris = load_iris()
X = iris.data
y = iris.target
X_train,X_test,y_train,y_test,= train_test_split(X,y,test_size = 0.3)

#2、模型训练及预测
model = neighbors.KNeighborsClassifier(n_neighbors = 3)
model.fit(X_train,y_train)
print('Predict_result:',model.predict(X_test))
print('True_result:',y_test)
print(model.predict_proba(X_test))
print('Accuracy:',model.score(X_test,y_test,sample_weight = None))

Predict_result: [1 2 2 1 0 0 2 1 2 0 1 0 0 2 1 2 1 2 0 2 0 1 1 1 1 2 1 1 0 2 0 1 0 1 2 0 2
 0 1 1 0 0 2 1 2]
True_result: [1 1 2 1 0 0 2 1 2 0 1 0 0 2 1 2 1 2 0 2 0 1 1 1 1 2 1 1 0 2 0 1 0 1 2 0 1
 0 1 1 0 0 2 1 2]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]
Accuracy: 0.9555555555555556
