# 朴素贝叶斯分类

## 自己编写实现

### 导入相关模块和包

In [2]:
#设置中文编码
#coding:utf-8
# 极大似然估计  朴素贝叶斯算法
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

### 定义主函数和NaiveBayes类

In [ ]:
if __name__ == '__main__':
    NB = NaiveBayes()
    trainData , labels, testData, testlabels = NB.getTrainSet()
    NB.test(trainData , labels, testData, testlabels)

In [ ]:
class NaiveBayes():
    #获取数据集并处理
    def getTrainSet(self):
        return trainData , labels, testData, testlabels
    
    #计算贝叶斯公式各概率及分类
    def classify(self,trainData ,labels,features):
        pass
    
    #查看分类结果
    def test(trainData , labels, testData, testlabels):
        pass

### 定义getTrainSet函数：读取并切分数据集

In [3]:
def getTrainSet(self):
        dataset = pd.read_csv('Iris.csv')
        #重命名各属性名称
        dataset = dataset.rename(columns = {'5.1':'Feature_1',
                         '3.5':'Feature_2',
                         '1.4':'Feature_3',
                         '0.2':'Feature_4',
                         'Iris-setosa':'labels'})
        datasetNP = np.array(dataset)
        X = datasetNP[:,:-1]
        y = datasetNP[:,-1]
        trainData, testData, labels,testlabels = train_test_split(X,y,test_size = 0.3)
        return trainData, labels, testData, testlabels


In [12]:
dataset = pd.read_csv('Iris.csv')
dataset = dataset.rename(columns = {'5.1':'Feature_1',
                         '3.5':'Feature_2',
                         '1.4':'Feature_3',
                         '0.2':'Feature_4',
                         'Iris-setosa':'labels'})
dataset.head(10)

Feature_1  Feature_2  Feature_3  Feature_4       labels
0        4.9        3.0        1.4        0.2  Iris-setosa
1        4.7        3.2        1.3        0.2  Iris-setosa
2        4.6        3.1        1.5        0.2  Iris-setosa
3        5.0        3.6        1.4        0.2  Iris-setosa
4        5.4        3.9        1.7        0.4  Iris-setosa
5        4.6        3.4        1.4        0.3  Iris-setosa
6        5.0        3.4        1.5        0.2  Iris-setosa
7        4.4        2.9        1.4        0.2  Iris-setosa
8        4.9        3.1        1.5        0.1  Iris-setosa
9        5.4        3.7        1.5        0.2  Iris-setosa

### 定义classify函数，计算各概率及分类

- 1、求先验概率p(yi)
- 2、求每个特征和每个标签对应的联合概率 p(xi,yi)
- 3、求每个特征在每个标签下的条件概率p(xi|yi)
- 4、求p(x|y),的连乘式
- 5、贝叶斯公式计算P(yi|X)=P(X|yi)p(yi)，求maxP(yi|X)得到分类

In [22]:
def classify(self,trainData ,labels,features):
        #1、
        labels = list(labels)
        P_y ={}
        for label in labels:
            P_y[label] = labels.count(label)/float(len(labels))
            
        #2/
        P_xy = {}
        for y in P_y.keys():
            y_index = [i for i,label in enumerate(labels) if label == y]
            for j in range(len(features)):
                x_index = [i for i,feature in enumerate(features) if feature == features[j]]
                xy_count = len(set(x_index)) & len(set(y_index))
                P_key = str(features[j])+ '*' + str(y)
                P_xy[P_key] = xy_count / float(len(labels))
                           
        #3/求条件概率
        P = {}                   
        for i in P_y.keys():
            for x in features:
                pkey = str(x) + '|' + str(y)
                p[pkey] = P_xy[str(x) + '*' + str(y)] / float(P_y[y])
        
        #计算每条数据集所属类别的概率
        F = {}
        for y in P_y:
            F[y] = P_y[y]
            for x in features:
                F[y] = F[y] * P[str(x) + '*' + str(y)]
                
        features_label = max(F,key = F.get)
        return features_label

### 定义test函数，查看训练结果及准确率

In [ ]:
def test(self,trainData,labels,testData,testlabels):
    correct = 0
    for i in range(len(testData)):
        features = testData[i]
        result = nb.classify(trainData ,labels,features)
        print(features,'属于'，result)
        if result == testlabels[i]:
            correct += 1
    accuracy = correct / float(len(testlabels))
    print('准确率:',accuracy)

### 完整代码，并查看训练结果

In [23]:
class NaiveBayes(object):
     def getTrainSet(self):
        dataset = pd.read_csv('Iris.csv')
        dataset = dataset.rename(columns = {'5.1':'Feature_1',
                         '3.5':'Feature_2',
                         '1.4':'Feature_3',
                         '0.2':'Feature_4',
                         'Iris-setosa':'labels'})
        datasetNP = np.array(dataset)
        X = datasetNP[:,:-1]
        y = datasetNP[:,-1]
        trainData, testData, labels,testlabels = train_test_split(X,y,test_size = 0.3)
        return trainData, labels, testData, testlabels

     def classify(self, trainData, labels, features):
        #求labels中每个label的先验概率
        labels = list(labels)
        #转换为list类型
        P_y = {}
        #用字典存入label及其概率
        for label in labels:
            P_y[label] = labels.count(label)/float(len(labels))
            # p = count(y) / count(Y)

        #求label与feature同时发生的概率
        P_xy = {}
        for y in P_y.keys():
            y_index = [i for i, label in enumerate(labels) if label == y]
            # labels中出现y值的所有数值的下标索引
            for j in range(len(features)):
                # features[0] 在trainData[:,0]中出现的值的所有下标索引
                x_index = [i for i, feature in enumerate(trainData[:,j]) if feature == features[j]]
                xy_count = len(set(x_index) & set(y_index))
                # set(x_index)&set(y_index)列出两个表相同的元素
                pkey = str(features[j]) + '*' + str(y)
                P_xy[pkey] = xy_count / float(len(labels))

        #求条件概率
        P = {}
        for y in P_y.keys():
            for x in features:
                pkey = str(x) + '|' + str(y)
                P[pkey] = P_xy[str(x)+'*'+str(y)] / float(P_y[y])
                #P[X1/Y] = P[X1Y]/P[Y]

        #求testData每条样例所属类别
        F = {}
        #testData每条样例属于各个类别的概率
        for y in P_y:
            F[y] = P_y[y]
            for x in features:
                F[y] = F[y]*P[str(x)+'|'+str(y)]
                #P[y|X] = P[X|y]*P[y]/P[X]，分母相等，比较分子即可，
                # 所以有F=P[X/y]*P[y]=P[x1/Y]*P[x2/Y]*P[x3|y]*P[x4|y]*P[y]

        features_label = max(F, key=F.get)
        #概率最大值对应的类别
        return features_label

     def test(self,trainData, labels, testData, testlabels):
            correct = 0
            for i in range(len(testData)):
                # Outlook Temperature Humidity Wind
                features = testData[i]
                # 该特征应属于哪一类
                result = nb.classify(trainData, labels, features)
                print(features, '属于', result)
                if nb.classify(trainData, labels, testData[i]) == testlabels[i]:
                    correct += 1
            accuracy = correct / float(len(testlabels))
            print('准确率:',accuracy)

if __name__ == '__main__':
            nb = NaiveBayes()
            # 训练数据,测试数据
            trainData, labels, testData, testlabels = nb.getTrainSet()
            nb.test(trainData, labels, testData, testlabels)

[5.4 3.9 1.7 0.4] 属于 Iris-setosa
[5.8 2.7 4.1 1.0] 属于 Iris-versicolor
[5.5 4.2 1.4 0.2] 属于 Iris-setosa
[6.6 2.9 4.6 1.3] 属于 Iris-setosa
[5.4 3.4 1.5 0.4] 属于 Iris-setosa
[6.3 3.3 6.0 2.5] 属于 Iris-setosa
[6.1 2.8 4.7 1.2] 属于 Iris-versicolor
[6.6 3.0 4.4 1.4] 属于 Iris-setosa
[6.7 3.0 5.0 1.7] 属于 Iris-setosa
[6.7 3.1 4.7 1.5] 属于 Iris-versicolor
[5.7 3.0 4.2 1.2] 属于 Iris-versicolor
[5.1 3.8 1.6 0.2] 属于 Iris-setosa
[6.4 3.2 5.3 2.3] 属于 Iris-virginica
[5.5 2.4 3.8 1.1] 属于 Iris-setosa
[6.7 3.0 5.2 2.3] 属于 Iris-virginica
[6.3 2.5 5.0 1.9] 属于 Iris-virginica
[7.2 3.0 5.8 1.6] 属于 Iris-setosa
[4.8 3.0 1.4 0.3] 属于 Iris-setosa
[5.1 3.8 1.5 0.3] 属于 Iris-setosa
[5.4 3.9 1.3 0.4] 属于 Iris-setosa
[7.3 2.9 6.3 1.8] 属于 Iris-setosa
[4.3 3.0 1.1 0.1] 属于 Iris-setosa
[6.7 3.3 5.7 2.5] 属于 Iris-setosa
[5.6 2.5 3.9 1.1] 属于 Iris-versicolor
[4.4 2.9 1.4 0.2] 属于 Iris-setosa
[5.0 3.5 1.6 0.6] 属于 Iris-setosa
[5.8 2.7 3.9 1.2] 属于 Iris-versicolor
[5.1 3.4 1.5 0.2] 属于 Iris-setosa
[4.9 2.5 4.5 1.7] 属于 Iris-setosa
[4.9 2.4 3

## 调用sklearn函数的NaiveBayes算法

https://scikit-learn.org/stable/modules/naive_bayes.html

### Gaussian Naive Bayes对于高斯分布的数据

In [46]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
X = iris.data
y = iris.target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

gnb = GaussianNB()
y_predict = gnb.fit(X_train,y_train).predict(X_test)

print('Number of mislabeled points out of a total %d points: %d'
     %(iris.data.shape[0],(y_test != y_predict).sum()))
print('Accuracy:',((y_test == y_predict).sum()/len(y_predict)))

Number of mislabeled points out of a total 150 points: 2
Accuracy: 0.9555555555555556


### multinominalNB 对于分类型数据，用于文本分类

### Bernoulli NB

In [ ]:
from sklearn.naive_bayes import BernoulliNB
nb = BernoulliNB()
nb.fit(X,y)